Introduce -t option

diff --git a/diff1 b/diff1
--- a/diff1
+++ b/diff1
@@ -30,6 +30,7 @@ __cache_dir=
 _data_file=
 _path=
 __package=
+__track_unknown_entities=no
 
 pkg_backend=rpm
 reporter=diff
@@ -50,7 +51,7 @@ function print_usage
     echo "	$0  [--mtime] DATA_FILE"
     echo "	$0  [--list|-l] [--mtime] DATA_DIR"
     echo "	$0  [--mtime] --path=PATH|--root=ROOT DATA_{FILE|DIRECTORY}"
-    echo "	$0  --package=PACKAGE"
+    echo "	$0  [--track-unknown-entities|-t] --package=PACKAGE"
     echo
     echo "COMMON OPTIONS: "
     echo "	[--yumdownloader-flags=YUMDOWNLOADER_FLAGS]"
@@ -137,6 +138,9 @@ function parse_arguments
 	    --ignore-overrides)
 	        ignore_overrides=1
 		;;
+	    --track-unknown-entities|-t)
+		__track_unknown_entities=yes
+		;;
 	    *)
 		break
 		;;
@@ -200,7 +204,7 @@ function parse_arguments
     fi
 
     if ! [ -r $_data_file ]; then
-	echo " # $0: no readable: $_data_file" 1>&2
+	echo "=== $0: no readable: $_data_file" 1>&2
 	exit 2
     fi
 
@@ -246,6 +250,9 @@ function diff1_package
     local package=$1
     shift 1
 
+    local track_unknown_entities=$1
+    shift 1
+
     local files
     local status=0
     
@@ -260,10 +267,16 @@ function diff1_package
 	if [[ -d "$f" ]]; then
 	    for xf in $(find "$f"); do
 		if ! rpm -qf $xf > /dev/null 2>&1; then
-		    echo " # UNKNOWN FILE: " $xf
+		    if [ -d $xf ]; then
+			echo "=== UNKNOWN DIR: " $xf
+		    else
+			echo "=== UNKNOWN FILE: " $xf
+		    fi
 		fi
 	    done
-	    continue
+	    if [[ "$track_unknown_entities" != yes ]]; then
+		continue
+	    fi
 	fi
 	$0 "$@" "${f}"
 	case $? in
@@ -307,7 +320,10 @@ function main
 	prepare_cache_dir
 	${pkg_backend}_diff1 $_data_file $_path
     else
-	diff1_package "${__package}" ${*/--package=*}
+	local p=${*/--package=*}
+	p=${p/-t}
+	p=${p/--track-unknown-entities}
+	diff1_package "${__package}" "${__track_unknown_entities}" ${p}
     fi
     
     return $?
@@ -379,23 +395,23 @@ function rpm_report_diff
     fi
 
     if ! [ -e $temp/$path ]; then
-	echo " # cannot find $file in rpm archive($pkg_file)" 1>&2
+	echo "=== cannot find $file in rpm archive($pkg_file)" 1>&2
 	return 2
     fi
 
     if [ -f $file ] || ( [ -d $file ] && [ $file != $path ] ); then
 	(
 	    cd $temp
-	    # echo " # diff ${diff_flags} ${path:1} $file # (pwd: $temp)"
+	    # echo "=== diff ${diff_flags} ${path:1} $file # (pwd: $temp)"
 	    mydiff ${diff_flags} ${path:1} $file 
 	    exit $?
 	)
 	status=$?
 	if [ $status = 0 ]; then
 	    if [ "${path}" = "${file}" ]; then
-		[ -z "$quiet" ] && echo " # NO CHANGE in $file"
+		[ -z "$quiet" ] && echo "=== NO CHANGE in $file"
 	    else
-		[ -z "$quiet" ] && echo " # NO CHANGE in $path -> $file"
+		[ -z "$quiet" ] && echo "=== NO CHANGE in $path -> $file"
 	    fi
 	fi
     elif [ "$list" = yes ]; then
@@ -447,13 +463,15 @@ function rpm_report_diff
 		    status=$r
 		fi
 	    elif rpm -qf ${elt} > /dev/null 2>&1; then
-		echo " # Skip ${elt} because it is owned by $(rpm -qf ${elt})"
+		echo "=== Skip ${elt} because it is owned by $(rpm -qf ${elt})"
 	    elif [[ ${elt} == *.rpmsave ]] \
 	      || [[ ${elt} == *.rpmnew ]]  \
 	      || [[ ${elt} == *.rpmorig ]]; then
-		echo " # Skip ${elt} because it may be generated by rpm command"
+		echo "=== Skip ${elt} because it may be generated by rpm command"
+	    elif [[ -d ${elt} ]]; then
+		echo "=== Skip ${elt} because it is a directory"
 	    else
-		echo " # Compare ${elt} with /dev/null because it is not owned by any package"
+		echo "=== Compare ${elt} with /dev/null because it is not owned by any package"
 		mydiff ${diff_flags} /dev/null ${elt}
 		r=$?
 		if [ $status = 0 ]; then
