Handle the case when opm is not found.

diff --git a/diff1 b/diff1
--- a/diff1
+++ b/diff1
@@ -270,8 +270,17 @@ function main
 
     
     if [ -z "${__package}" ]; then
-	if [ -z "${ignore_overrides}" ] && opm -qf $_path > /dev/null 2>&1; then
-	    pkg_backend=opm
+	if [ -z "${ignore_overrides}" ] then
+	    if which opm > /dev/null 2>&1; then
+		echo "cannot find opm command" 1>&2
+		exit 2
+	    fi
+	    if opm -qf $_path > /dev/null 2>&1; then
+		pkg_backend=opm
+	    else
+		pkg_backend=rpm
+	    fi
+	    
 	else
 	    pkg_backend=rpm
 	fi
